[package]
name = "glyph-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
glyph-core.workspace = true
glyph-trie.workspace = true

thiserror.workspace = true
mlua.workspace = true
serde.workspace = true
tokio.workspace = true
parking_lot.workspace = true

[lints]
workspace = true
