[package]
name = "glyph-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true

bitflags = "2.9.1"
clap = { version = "4.5.41", features = ["derive"] }
