[package]
name = "glyph-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing.workspace = true
thiserror.workspace = true

ropey = "1.6.1"
slotmap = "1.0.7"
tree-sitter = "0.24.4"
tree-sitter-rust = "0.23.2"
streaming-iterator = "0.1.9"
