[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
toml.workspace = true

tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"
dirs = "5.0.1"
