[package]
name = "glyph-vim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
glyph-core.workspace = true
glyph-trie.workspace = true
tracing.workspace = true